// <auto-generated />
using System;
using Desafio.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240515030505_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio.Domain.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("CityEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("Main")
                        .HasColumnType("boolean");

                    b.Property<string>("NeighborhoodName")
                        .HasColumnType("text");

                    b.Property<Guid?>("StateEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityEntityId");

                    b.HasIndex("StateEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("AddressEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("StateEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CityEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ClientExcluded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClientUserEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserEntityId");

                    b.ToTable("ClientEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.PreRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<bool>("TagValidation")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenValidation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PreRegistrationEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.PreUpdateEmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenValidation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("PreUpdateEmailEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("RefreshTokenEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ClientEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Fine")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("InitialDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int?>("Plan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrevisionFinalDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClientEntityId");

                    b.ToTable("ServiceEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.StateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FederativeUnit")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StateEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptTermsDate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CNHType")
                        .HasColumnType("integer");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("GenreType")
                        .HasColumnType("integer");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserCNH")
                        .HasColumnType("text");

                    b.Property<string>("UserCnpj")
                        .HasColumnType("text");

                    b.Property<bool?>("UserExcluded")
                        .HasColumnType("boolean");

                    b.Property<string>("UserMail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserNickName")
                        .HasColumnType("text");

                    b.Property<string>("UserPhone")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserTypeEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeEntityId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.UserTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastModified")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserTypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserTypeEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.AddressEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.CityEntity", "CityEntity")
                        .WithMany()
                        .HasForeignKey("CityEntityId");

                    b.HasOne("Desafio.Domain.Entities.StateEntity", "StateEntity")
                        .WithMany()
                        .HasForeignKey("StateEntityId");

                    b.HasOne("Desafio.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany("UserAddressesList")
                        .HasForeignKey("UserEntityId");

                    b.Navigation("CityEntity");

                    b.Navigation("StateEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.ClientEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.UserEntity", "ClientUserEntity")
                        .WithMany()
                        .HasForeignKey("ClientUserEntityId");

                    b.Navigation("ClientUserEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.PreUpdateEmailEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.ServiceEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.ClientEntity", "ClientEntity")
                        .WithMany("ServicesList")
                        .HasForeignKey("ClientEntityId");

                    b.Navigation("ClientEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("Desafio.Domain.Entities.UserTypeEntity", "UserTypeEntity")
                        .WithMany()
                        .HasForeignKey("UserTypeEntityId");

                    b.Navigation("UserTypeEntity");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.ClientEntity", b =>
                {
                    b.Navigation("ServicesList");
                });

            modelBuilder.Entity("Desafio.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("UserAddressesList");
                });
#pragma warning restore 612, 618
        }
    }
}
